# Generated by Django 4.2.1 on 2023-12-28 10:41

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laundry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('client', models.CharField(max_length=250)),
                ('contact', models.CharField(blank=True, max_length=250, null=True)),
                ('total_amount', models.FloatField(max_length=15)),
                ('tendered', models.FloatField(max_length=15)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In-progress', 'In-progress'), ('Done', 'Done'), ('Picked Up', 'Picked Up')], default='Pending', max_length=100)),
                ('payment', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid')], default='Unpaid', max_length=100)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('delivery_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LaundryshopeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_address', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('shop_name', models.CharField(help_text='Enter the shop name', max_length=100, unique=True)),
                ('shop_img', models.ImageField(blank=True, default=None, null=True, upload_to='shop_images/')),
            ],
        ),
        migrations.CreateModel(
            name='LaundryUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=1000)),
                ('pin', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('state', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('password', models.CharField(default=0, max_length=200)),
                ('img', models.ImageField(blank=True, default=None, null=True, upload_to='user_images/')),
                ('user_type', models.CharField(choices=[('admin', 'admin'), ('laundry_shop_user', 'laundry_shop_user'), ('customer', 'customer')], default='customer', max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Order_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_id', models.CharField(max_length=100)),
                ('shop_name', models.CharField(max_length=1000)),
                ('clint_id', models.CharField(max_length=1000)),
                ('clint_name', models.CharField(max_length=1000, null=True)),
                ('contact', models.CharField(blank=True, max_length=250, null=True)),
                ('clint_address', models.CharField(blank=True, max_length=1000)),
                ('category', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200, null=True), blank=True, default=list, size=None)),
                ('order_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_amount', models.FloatField(blank=True, max_length=15, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In-progress', 'In-progress'), ('Done', 'Done'), ('Picked Up', 'Picked Up')], default='Pending', max_length=100)),
                ('payment', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid')], default='Unpaid', max_length=100)),
                ('payment_status', models.CharField(choices=[('ONLINE', 'ONLINE'), ('COD', 'COD')], default='COD', max_length=100)),
                ('orderId', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('paymentId', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('paymentsignature', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivery_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Laundrytype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('price', models.FloatField(default=0, max_length=15)),
                ('status', models.CharField(choices=[('active', 'Active'), ('active', 'Inactive')], default='active', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laundry.laundryshopeuser')),
            ],
        ),
        migrations.AddField(
            model_name='laundryshopeuser',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laundry_shop_user', to='laundry.laundryuser'),
        ),
    ]
